### PR TITLE
Fixed: optional amount when place buy

### PR DESCRIPTION
**Pull request by Pethical**

### CODE REVIEW

**Comment by bchavez** [comment]
Hi there,

Thank you for the PR!

Do you have a link to any documentation that allows the amount field to be optional? If not, do you have any JSON payloads that you can post that shows the successful request / response bodies?

Thanks,
Brian

**Comment by Pethical** [comment]
Hi,
Yes.

https://developers.coinbase.com/api/v2#place-buy-order

You can specify amount or total, but not both.

Regards,
 Peter

**Comment by bchavez** [comment]
Cool. Thank you, I'll have a release for you shortly.

**Comment by bchavez** [comment]
@Pethical , pushed Coinbase v5.1.2 with your fix here: https://www.nuget.org/packages/Coinbase/5.1.2

Thanks again!

**Pull request merged**
