### PR TITLE
Update Objects.cs

### PR DESCRIPTION
**Pull request by bheesbeen**
Also the CreatedAt and UpdatedAt properties form Buy nullable

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @bheesbeen,

Thank you for the PR. Do you have the JSON response where these fields are nullable? I'd like to write some unit tests for these issues.

Thanks,
Brian

**Comment by bheesbeen** [comment]
Brian,I am sorry, i just got the json exception pointing me to the created_at propery.I did not capture any json.Bert
-------- Oorspronkelijk bericht --------Van: Brian Chavez <notifications@github.com> Datum: 28-02-19  18:31  (GMT+01:00) Aan: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: bheesbeen <heesbeen@inzo.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [bchavez/Coinbase] Update Objects.cs (#53) Hi @bheesbeen,
Thank you for the PR. Do you have the JSON response where these fields are nullable? I'd like to write some unit tests for these issues.
Thanks,
Brian

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #53: Hi @bheesbeen,\r\n\r\nThank you for the PR. Do you have the JSON response where these fields are nullable? I'd like to write some unit tests for these issues.\r\n\r\nThanks,\r\nBrian"}],"action":{"name":"View Pull Request","url":"https://github.com/bchavez/Coinbase/pull/53#issuecomment-468363289"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bchavez/Coinbase/pull/53#issuecomment-468363289",
"url": "https://github.com/bchavez/Coinbase/pull/53#issuecomment-468363289",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bchavez** [comment]
Hi Bert,

I've marked all `.CreatedAt` and `.UpdatedAt` fields as nullable in the object models. Hopefully that resolves these kinds of issues once and for all (related #52).

You can get the new **Coinbase** `v5.0.8` bits here: https://www.nuget.org/packages/Coinbase/5.0.8

Thanks again for your help!
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by bheesbeen** [comment]
Thanks!
-------- Oorspronkelijk bericht --------Van: Brian Chavez <notifications@github.com> Datum: 28-02-19  19:14  (GMT+01:00) Aan: bchavez/Coinbase <Coinbase@noreply.github.com> Cc: bheesbeen <heesbeen@inzo.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [bchavez/Coinbase] Update Objects.cs (#53) Hi Bert,

I've marked all .CreatedAt and .UpdatedAt fields as nullable in the object models. Hopefully that resolves these kinds of issues once and for all (related #52).

You can get the new Coinbase v5.0.8 bits here: https://www.nuget.org/packages/Coinbase/5.0.8

Thanks again for your help!

Brian

🚶 😎 "So don't delay... act now supplies are running out..."



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bchavez/Coinbase","title":"bchavez/Coinbase","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bchavez/Coinbase"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bchavez in #53: Hi Bert,\r\n\r\nI've marked all `.CreatedAt` and `.UpdatedAt` fields as nullable in the object models. Hopefully that resolves these kinds of issues once and for all (related #52).\r\n\r\nYou can get the new **Coinbase** `v5.0.8` bits here: https://www.nuget.org/packages/Coinbase/5.0.8\r\n\r\nThanks again for your help!\r\nBrian\r\n\r\n:walking: :sunglasses: ***[\"So don't delay... act now supplies are running out...\"](https://www.youtube.com/watch?v=LQj--Kjn0z8)***"}],"action":{"name":"View Pull Request","url":"https://github.com/bchavez/Coinbase/pull/53#issuecomment-468378529"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/bchavez/Coinbase/pull/53#issuecomment-468378529",

"url": "https://github.com/bchavez/Coinbase/pull/53#issuecomment-468378529",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Pull request merged**
