### PR TITLE
Adding Notification Event, fixing transaction bug and adding Superficial DI

### PR DESCRIPTION
**Pull request by granthoff1107**

### CODE REVIEW

**Comment by granthoff1107** [comment]
Note:  the wallet:addresses:new-payment description has been modified to more accurately reflect the behavior of the api.

The original description is:
     New payment has been made to a Bitcoin address
Our Description is:
     New payment has been made to a Bitcoin address

The the api documentation is misleading because it implies only bitcoin addresses work.  While I've been testing using Ethereum and these work as well.

**Comment by bchavez** [comment]
Fantastic work. Thanks Grant. I'll publish a new release a new version shortly.

**Comment by bchavez** [comment]
Hey Grant,

Changes are now live: https://www.nuget.org/packages/Coinbase/5.0.3

Thanks again,
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by granthoff1107** [comment]
Thanks I’m still sorting out a few thing with notifications. I may have
another pull request in a few days.

I’ve been trying to get Coinbase to answer some of my questions but there
not so timely,

Just as a heads up, minor detail but I think the user agent is still
posting as version 2, I saw it in my request bin when testing notifications

**Comment by bchavez** [comment]
Hm. Authenticated requests should contain the `User-Agent` header value as shown in the screenshot below, but it does seem `Data` requests don't. I'll get that fixed.

Perhaps the `v2` you were seeing was in the query string?

fiddler_2410

**Comment by granthoff1107** [comment]
When I get back to my computer I’ll pull down what I was seeing on request
bin

**Pull request merged**
