### PR TITLE
Adding Support For OAuth

### PR DESCRIPTION
**Pull request by granthoff1107**
I've added support for OAuth.
Adding Simple Error Handling.
Simplified Constructors
Everything should be backwards comaptible

This method seemed wierd to me seemed like this should be post only why would someone add a json body to a GET Request?:

    public virtual CoinbaseResponse SendRequest(string endpoint, object body, Method httpMethod = Method.POST)
    {
        var client = CreateClient();

        var req = CreateRequest(endpoint, httpMethod)
                .AddJsonBody(body);
        //...

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @granthoff1107,

Could you please try out `v5.0.0-beta-1`. I've added OAuth support.

https://www.nuget.org/packages/Coinbase/5.0.0-beta-1

Check the [README](https://github.com/bchavez/Coinbase) page for details.. Please let me know if it works.

Thanks,
Brian

:black_circle: :dizzy: ***["Black magic... bla-a-a-ack... black magic..."](https://www.youtube.com/watch?v=3SnlsTtUZK0)***

**Comment by granthoff1107** [comment]
I’m reviewing this from my phone so it’s hard to see everything.  But it
looks like you don’t provide raw access to the request from the api
endpoints.

That’s fine in most cases but when using the Endpoints from OAuth
occasionally you’ll need to supply a CB-2FA-TOKEN header to add 2 factor
and replay a request such as in the Transfer api

**Comment by granthoff1107** [comment]
Thanks, this saves me a lot of work.
I'm in the process of refactoring my local examples.
I only found two Issues with the current beta. 
   1.  OAuth Requires 2FA, I think its only for the Transactions api.  
   2.  I don't see a way to get the next page in the List Api's

When I'm done refactoring my local examples I can make a pull request.  
If you get a chance let me know your preference on how I should write it.
    Should the Transactions Api Take in 2Fa Token. 
    Or would it be better to allow an options param which has an action to to modify the FlurlRequest,

the later would be more versatile in case in the the end users need  to add other headers etc. 

Once, I get my examples updated I'll start testing more but thanks for putting out the beta when you did!

**Comment by bchavez** [comment]
I just now pushed some code that promotes the `CoinbaseApi` as a `FlurlClient`.

So, usage should remain the same, but you can mutate the headers before sending your request. IE:

```
//using OAuth Token
var client = new CoinbaseApi(new OAuthConfig{ OAuthToken = "..." });
var create = new CreateTransaction
   {
      Amount = 1.0m,
      Currency = "BTC"
   };
var response = await client
    .WithHeader(TwoFactorToken, "ffff")
    .Transactions.SendMoneyAsync("accountId", create);
```

Hold tight for a few more minutes and I'll send out another beta release with the updated changes. :sunglasses: 

:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***

**Comment by granthoff1107** [comment]
Thanks, this should work perfect.  I’ll test this out in a bit and let you
know

**Comment by bchavez** [comment]
Hi Grant,

Just published `v5.0.0-beta-2` here:
https://www.nuget.org/packages/Coinbase/5.0.0-beta-2

Let me know how it goes. If all goes well, I'll promote beta-2 to as the latest release.

Docs have been updated on the [README page](https://github.com/bchavez/Coinbase)

Thanks,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Pull request closed without merging**
